-- clear tables --
DROP TABLE IF EXISTS PROFESSOR;
DROP TABLE IF EXISTS DEPARTMENT;
DROP TABLE IF EXISTS COURSE;
DROP TABLE IF EXISTS PREREQ;
DROP TABLE IF EXISTS SECTION;
DROP TABLE IF EXISTS STUDENT;
DROP TABLE IF EXISTS MINOR;
DROP TABLE IF EXISTS ENROLL;

-- creating tables --
CREATE TABLE PROFESSOR (
    SSN INT PRIMARY KEY,
    PNAME TEXT,
    STREET TEXT,
    CITY TEXT,
    STATE TEXT,
    ZIPCODE INT,
    AREACODE INT,
    PNUMBER INT,
    SEX TEXT,
    TITLE TEXT,
    SALARY FLOAT,
    DEGREES TEXT
);

CREATE TABLE DEPARTMENT (
    DNUM TEXT PRIMARY KEY,
    DNAME TEXT,
    PHONE_NUM INT,
    LOCATION TEXT,
    CHAIRPERSON INT,
    FOREIGN KEY (CHAIRPERSON) references PROFESSOR(SSN)
);

CREATE TABLE COURSE (
    CNUM TEXT PRIMARY KEY,
    TITLE TEXT,
    TEXTBOOK TEXT,
    UNITS INT,
    DEPARTMENT TEXT,
    FOREIGN KEY (DEPARTMENT) references DEPARTMENT(DNUM)
);

CREATE TABLE PREREQ (
    CNUM TEXT,
    NEEDS TEXT,
    PRIMARY KEY (CNUM, NEEDS),
    FOREIGN KEY (CNUM) references COURSE(CNUM),
    FOREIGN KEY (NEEDS) references COURSE(CNUM)
);

CREATE TABLE SECTION (
    SNUM INT,
    CNUM TEXT,
    CLASSROOM TEXT,
    NUM_SEATS INT,
    DAYS TEXT,
    BEGIN_TIME TEXT,
    END_TIME TEXT,
    PROFESSOR INT,
    PRIMARY KEY (SNUM, CNAME),
    FOREIGN KEY (CNUM) references COURSE(CNUM),
    FOREIGN KEY (PROFESSOR) references PROFESSOR(SSN)
);

CREATE TABLE STUDENT (
    CWID INT PRIMARY KEY,
    FNAME TEXT,
    LNAME TEXT,
    ADDRESS TEXT,
    PHONE_NUM INT,
    MAJOR TEXT,
    FOREIGN KEY (MAJOR) references DEPARTMENT(DNUM)
);

CREATE TABLE MINOR (
    STUDENT_ID INT,
    DEPARTMENT TEXT,
    PRIMARY KEY (STUDENT_ID, DEPARTMENT),
    FOREIGN KEY (CWID) references STUDENT(CWID),
    FOREIGN KEY (DEPARTMENT) references DEPARTMENT(DNUM)
);

CREATE TABLE ENROLL (
    CWID TEXT,
    SNUM TEXT,
    CNUM TEXT,
    GRADE TEXT,
    PRIMARY KEY (CWID, SNUM, CNUM),
    FOREIGN KEY (CWID) references STUDENT(CWID),
    FOREIGN KEY (SNUM) references SECTION(SNUM),
    FOREIGN KEY (CNUM) references SECTION(CNUM)
);

-- inserting data into tables --
