-- Professor Queries
-- Given a professor's SSN
SELECT S.CLASSROOM, S.DAYS, S.BEGIN_TIME, S.END_TIME, C.TITLE
FROM SECTION S, PROFESSOR P, COURSE C
WHERE S.PROFESSOR=P.SSN AND P.SSN=INPUT_SSN AND C.CNUM=S.CNUM;

-- Given a course number and section number
SELECT E.Grade, COUNT(*)
FROM SECTION S, COURSE C, ENROLL E
WHERE C.CNUM=INPUT_COURSE AND S.SNUM=INPUT_SECTION AND
      S.CNUM=C.CNUM AND S.SNUM=E.SNUM AND S.CNUM=E.CNUM
GROUP BY E.Grade;

-- Student Queries
-- Given a course number
SELECT S.SNUM, S.CLASSROOM, S.BEGIN_TIME, S.END_TIME, COUNT(*)
FROM SECTION S, ENROLL E
WHERE S.CNUM=INPUT_CNUM AND S.SNUM=E.SNUM AND S.CNUM=E.CNUM
GROUP BY S.SNUM

-- Given CWID
SELECT C.TITLE, E.GRADE
FROM ENROLL E, COURSE C
WHERE E.CWID=INPUT_CWID AND E.CNUM=C.CNUM